const { existsSync, readFileSync } = require("fs");
const { getAppJson, test, getIconSizePNG } = require("./testHelpers");
const { appid: computeAppid } = require("./scripts/lib/slug");

const ICON_WIDTH_MIN = 100;
const ICON_WIDTH_MAX = 300;
const ICON_HEIGHT_MIN = 100;
const ICON_HEIGHT_MAX = 300;

// Apps whose appid predates (or diverges from) sha1(Str::slug(name, '')).
// These are grandfathered: their appid is a stable public identifier that
// existing Heimdall installs rely on, so it must not be "corrected". Most are
// renamed apps that kept the appid of their original name (e.g. TwoFAuth was
// "2FAuth", Dashdot was "dash."); VuPlus additionally uses a 32-char legacy id.
// Generated by the full disk scan; do not extend without a matching real app.
const APPID_EXCEPTIONS = new Set([
    "Audiobookshelf",
    "Dashdot",
    "FlexGet",
    "Hydrawise",
    "ISPConfig",
    "InfCloud",
    "Maintainerr",
    "OpenCCU",
    "Pinchflat",
    "Reaparr",
    "Seerr",
    "Threadfin",
    "TrueNAS",
    "TwoFAuth",
    "VuPlus",
    "Wizarr",
    "bitShake",
    "ntfy",
]);

// Apps that predate the enhanced-consistency convention. Monit and UniFi are
// flagged enhanced but use a getAvailableStats() pattern instead of
// implementing \App\EnhancedApps; VMwareESXi implements the interface while
// being flagged enhanced=false. Grandfathered so the suite stays green.
const ENHANCED_EXCEPTIONS = new Set(["Monit", "UniFi", "VMwareESXi"]);

const implementsEnhanced = (appDirectory) => {
    const phpFile = `${appDirectory}/${appDirectory}.php`;
    if (!existsSync(phpFile)) {
        return false;
    }
    return /implements\s+\\?App\\EnhancedApps/.test(
        readFileSync(phpFile).toString()
    );
};

const testApp = (appDirectory) => {
    global.appUnderTest = `${appDirectory}`;

    const appJson = getAppJson(appDirectory);
    const iconName = appJson.icon || "";

    // Icon tests
    test("should have an icon file", () => {
        return existsSync(`${appDirectory}/${iconName}`);
    });

    test("should have .png or .svg as icon file", () => {
        return iconName.endsWith(".svg") || iconName.endsWith(".png");
    });

    test("should have an Icon with max width 300px and max height 300px when PNG", () => {
        if (iconName.endsWith(".png")) {
            const iconSize = getIconSizePNG(`${appDirectory}/${iconName}`);

            const isWidthTooBig = iconSize.width > ICON_WIDTH_MAX;
            const isHeightTooBig = iconSize.height > ICON_HEIGHT_MAX;
            if (isWidthTooBig || isHeightTooBig) {
                console.log("Icon is too big:", iconSize);
            }

            return !isWidthTooBig && !isHeightTooBig;
        }
        return true;
    });

    test("should have an Icon with min width 100px and min height 100px when PNG", () => {
        if (iconName.endsWith(".png")) {
            const iconSize = getIconSizePNG(`${appDirectory}/${iconName}`);

            const isWidthTooSmall = iconSize.width < ICON_WIDTH_MIN;
            const isHeightTooSmall = iconSize.height < ICON_HEIGHT_MIN;
            if (isWidthTooSmall || isHeightTooSmall) {
                console.log("Icon is too small:", iconSize);
            }

            return !isWidthTooSmall && !isHeightTooSmall;
        }
        return true;
    });

    // app.json tests
    test("should have app.json file", () => {
        return existsSync(`${appDirectory}/app.json`);
    });

    test("should have name defined in app.json", () => {
        return typeof appJson.name === "string" && appJson !== "";
    });

    test("should have name matching the app directory name normalized", () => {
        return appJson.name.replaceAll(/[ -.:@]/g, "") === appDirectory;
    });

    test("should have a non-empty hexadecimal appid", () => {
        return (
            typeof appJson.appid === "string" &&
            /^[0-9a-f]+$/.test(appJson.appid)
        );
    });

    test("should have appid equal to sha1 of the name slug", () => {
        if (APPID_EXCEPTIONS.has(appDirectory)) {
            return true; // grandfathered stable identifier
        }
        return appJson.appid === computeAppid(appJson.name);
    });

    // Enhanced apps must ship config + livestats blades and implement the
    // EnhancedApps interface; foundation apps must do none of those.
    test("should be internally consistent about being enhanced", () => {
        if (ENHANCED_EXCEPTIONS.has(appDirectory)) {
            return true; // grandfathered inconsistency
        }
        const enhanced = appJson.enhanced === true;
        const hasConfig = existsSync(`${appDirectory}/config.blade.php`);
        const hasLive = existsSync(`${appDirectory}/livestats.blade.php`);
        const implementsEnh = implementsEnhanced(appDirectory);
        if (enhanced) {
            return hasConfig && hasLive && implementsEnh;
        }
        return !hasConfig && !hasLive && !implementsEnh;
    });

    // PHP file
    test("should have a php file", () => {
        return existsSync(`${appDirectory}/${appDirectory}.php`);
    });

    test("should have a Class with same name as directory", () => {
        const phpFile = `${appDirectory}/${appDirectory}.php`;
        if (!existsSync(phpFile)) {
            return false;
        }

        const phpFileContent = readFileSync(
            `${appDirectory}/${appDirectory}.php`
        ).toString();

        return phpFileContent.indexOf(`class ${appDirectory}`) !== -1;
    });

    test("should have the namespace based on the class name", () => {
        const phpFile = `${appDirectory}/${appDirectory}.php`;
        if (!existsSync(phpFile)) {
            return false;
        }

        const phpFileContent = readFileSync(
            `${appDirectory}/${appDirectory}.php`
        ).toString();

        return (
            phpFileContent.indexOf(
                `namespace App\\SupportedApps\\${appDirectory}`
            ) !== -1
        );
    });
};

// Cross-app invariants (run once over all directories).
const testGlobals = (directories) => {
    global.appUnderTest = "(all apps)";

    const byAppid = {};
    directories.forEach((dir) => {
        const appJson = getAppJson(dir);
        if (appJson.appid) {
            (byAppid[appJson.appid] = byAppid[appJson.appid] || []).push(dir);
        }
    });

    Object.entries(byAppid).forEach(([id, dirs]) => {
        test(`appid ${id} should be unique (used by: ${dirs.join(", ")})`, () => {
            return dirs.length === 1;
        });
    });
};

module.exports = {
    testApp,
    testGlobals,
    APPID_EXCEPTIONS,
    ENHANCED_EXCEPTIONS,
};
