"use strict";

/**
 * Slug / appid / folder derivation for Heimdall-Apps.
 *
 * The canonical Heimdall-Apps identifiers are generated by the (now retired)
 * Laravel request site. The two rules we must reproduce exactly are:
 *
 *   appid = sha1(Str::slug($name, ''))          // RequestController.php
 *   icon  = Str::slug($name, '') . '.' . $ext   // RequestController.php
 *
 * `Str::slug($title, '')` is Laravel's slug helper with an empty separator.
 * With the default English dictionary it:
 *   1. transliterates to ASCII (Str::ascii)
 *   2. removes the "flip" character ('-') -- runs collapse to the separator,
 *      which is empty here
 *   3. applies the default dictionary { '@' => 'at' }
 *   4. lower-cases and strips every character that is not a letter, number or
 *      whitespace
 *   5. collapses whitespace runs to the (empty) separator and trims
 *
 * The `@ => at` step is load-bearing: e.g. "Folding@Home" slugifies to
 * "foldingathome" (its shipped icon is foldingathome.svg, which proves the
 * dictionary was active when the app was generated).
 *
 * This module is used by the scaffolder, the request workflows and the CI
 * hardening tests, so it is a dependency-free pure module.
 */

const crypto = require("crypto");
const { toAscii } = require("./ascii");

/**
 * Reproduce Laravel `Str::slug($name, '')`.
 * @param {string} name
 * @returns {string}
 */
function slugify(name) {
    let s = toAscii(name);
    // Separator is empty; the "flip" character for '-' is removed.
    s = s.replace(/-+/g, "");
    // Default dictionary: '@' => separator.'at'.separator === 'at'.
    s = s.split("@").join("at");
    // Lower-case, then drop everything that is not a letter/number/whitespace.
    s = s.toLowerCase().replace(/[^a-z0-9\s]+/g, "");
    // Collapse whitespace to the empty separator.
    s = s.replace(/\s+/g, "");
    return s;
}

/**
 * appid = sha1 hex of the slug.
 * @param {string} name
 * @returns {string} 40-char lowercase hex
 */
function appid(name) {
    return crypto.createHash("sha1").update(slugify(name)).digest("hex");
}

/**
 * Repo folder name for an app.
 *
 * Matches the normalization enforced by apps.tests.js:
 *   appJson.name.replaceAll(/[ -.:@]/g, "") === appDirectory
 * The `[ -.]` part is a character range (0x20-0x2e): space and the common
 * punctuation that precedes '/'. Plus ':' and '@'.
 *
 * NOTE: this can leave characters that are not [A-Za-z0-9] (e.g. '+', '/',
 * '&', "'", unicode letters). Always gate the result through isValidFolder()
 * before touching the filesystem.
 * @param {string} name
 * @returns {string}
 */
function deriveFolder(name) {
    return String(name).replace(/[ -.:@]/g, "");
}

// A safe repo folder name: ASCII letters and digits only.
const FOLDER_RE = /^[A-Za-z0-9]+$/;

/**
 * @param {string} folder
 * @returns {boolean} true when folder is safe to use as a path segment
 */
function isValidFolder(folder) {
    return typeof folder === "string" && FOLDER_RE.test(folder);
}

/**
 * Canonical icon filename: the slug plus the (lower-cased, dot-prefixed)
 * extension. Reproduces RequestController's `$imagename.'.'.$extension`.
 * @param {string} name
 * @param {string} ext extension with or without a leading dot
 * @returns {string}
 */
function deriveIconName(name, ext) {
    const clean = String(ext).replace(/^\.+/, "").toLowerCase();
    return `${slugify(name)}.${clean}`;
}

module.exports = {
    slugify,
    appid,
    deriveFolder,
    isValidFolder,
    deriveIconName,
    FOLDER_RE,
};
